name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install FunPayAPI beautifulsoup4 customtkinter pyinstaller Pillow
    
    - name: Build exe
      run: |
        python -m PyInstaller --onefile --windowed --name=FunPayKeyChecker --hidden-import=customtkinter --hidden-import=FunPayAPI --hidden-import=bs4 --clean --noconfirm gui_main.py
    
    - name: Check exe
      run: |
        if (Test-Path "dist/FunPayKeyChecker.exe") {
          $size = (Get-Item "dist/FunPayKeyChecker.exe").Length / 1MB
          Write-Host "✅ EXE created successfully! Size: $([math]::Round($size, 1)) MB"
        } else {
          Write-Error "❌ EXE file not found"
          exit 1
        }
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/FunPayKeyChecker.exe
        body: |
          ## 🚀 FunPay Key Checker ${{ github.ref_name }}
          
          ### 📦 Скачать
          - **Windows EXE**: FunPayKeyChecker.exe (~35-40 MB)
          
          ### 🔧 Установка
          1. Скачайте FunPayKeyChecker.exe
          2. Запустите файл
          3. Настройте Golden Key в первой вкладке
          
          ### 🐛 Сообщить об ошибке
          [Создать Issue](https://github.com/${{ github.repository }}/issues/new)
          
          ### 👤 Разработчик
          @slonce70
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}