name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Installed packages:"
        pip list | findstr -i "funpay customtkinter pyinstaller pillow beautifulsoup"
        echo "Python and pip versions:"
        python --version
        pip --version
    
    - name: Create icon if missing
      run: |
        echo "Checking files..."
        if (Test-Path "gui_main.py") { echo "✅ gui_main.py exists" } else { echo "❌ gui_main.py missing" }
        if (Test-Path "icon.ico") { echo "✅ icon.ico exists" } else { echo "❌ icon.ico missing, creating..." ; python create_icon.py }
        if (Test-Path "requirements.txt") { echo "✅ requirements.txt exists" } else { echo "❌ requirements.txt missing" }
    
    - name: Build exe
      run: |
        echo "Starting PyInstaller build..."
        python -m PyInstaller --version
        python -m PyInstaller --onefile --windowed --name=FunPayKeyChecker --icon=icon.ico --hidden-import=customtkinter --hidden-import=FunPayAPI --hidden-import=bs4 --hidden-import=PIL --hidden-import=tkinter --collect-all=customtkinter --clean --noconfirm gui_main.py
        echo "Build completed, checking results..."
        if (Test-Path "dist") { echo "✅ dist folder exists" ; Get-ChildItem dist } else { echo "❌ dist folder missing" }
    
    - name: Check exe
      run: |
        if (Test-Path "dist/FunPayKeyChecker.exe") {
          $size = (Get-Item "dist/FunPayKeyChecker.exe").Length / 1MB
          Write-Host "✅ EXE created successfully! Size: $([math]::Round($size, 1)) MB"
        } else {
          Write-Error "❌ EXE file not found"
          exit 1
        }
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: dist/FunPayKeyChecker.exe
        body: |
          ## 🚀 FunPay Key Checker ${{ github.ref_name }}
          
          ### 📦 Скачать
          - **Windows EXE**: FunPayKeyChecker.exe (~35-40 MB)
          
          ### 🔧 Установка
          1. Скачайте FunPayKeyChecker.exe
          2. Запустите файл
          3. Настройте Golden Key в первой вкладке
          
          ### ✨ Особенности
          - Современный GUI с темной темой
          - Умный поиск ключей в заказах FunPay
          - Экспорт результатов в разных форматах
          - Защита от блокировки API
          
          ### 🐛 Сообщить об ошибке
          [Создать Issue](https://github.com/${{ github.repository }}/issues/new)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}